### ISSUE TITLE
Add stakater-charts helm repo to Chartcenter.io

### ISSUE THREAD

**Issue by rimusz** [stakater/stakater-charts#16]
Hi there,

Would you mind to open a PR in https://github.com/jfrog/chartcenter/blob/master/repos.yaml so Stakater helm charts
can be available in https://chartcenter.io?

Thank you

**Comment by ahmedwaleedmalik** [comment]
Hey @rimusz, just saw this. Added a PR there :) 
https://github.com/jfrog/chartcenter/pull/35
