### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [stakater/stakater-charts#3]
Hello i noticed your project is opensource and without a logo yet. I am a graphic designer and if you would like it, i contribute a logo design to your project. It's free of course.

**Comment by ahmadiq** [comment]
Hello @dee-y Thanks for the offer. We're already looking into getting the logo created. However, can you share your portfolio or other samples of your work.

**Comment by dee-y** [comment]
owk here is a few logos have made recently

![logotype_1a](https://user-images.githubusercontent.com/36637989/42908725-a48b0cd4-8ad9-11e8-8d6e-2ab9af5666d5.png)

![512px](https://user-images.githubusercontent.com/36637989/42908754-ba740208-8ad9-11e8-9384-7546feafd1fa.png)

![logotype 1](https://user-images.githubusercontent.com/36637989/42908906-1c99ab72-8ada-11e8-9e2c-04d7adc3f907.png)

![logotype](https://user-images.githubusercontent.com/36637989/42908920-2d24ab0e-8ada-11e8-978e-ca20ef9c227d.png)

**Comment by ahmadiq** [comment]
Thanks. we'll let you know in case we need a logo designed.

**Comment by dee-y** [comment]
Awesome!

**Comment by stakater-user** [comment]
@stakater-user Terraform Validate successful
